package com.myproject.exception;

public enum IMApiServiceExceptionType {
	INVALID_SEARCH_METADATA, 
	INVALID_REPORT_METADATA, 
	INTERNAL_ERROR, 
	INVALID_DATA_FOUND, 
	OBJECT_DOES_NOT_EXIST,
	USER_ATTRIBUTE_VALUE_NOT_FOUND,
	UNAUTHORIZED,
	REPORT_NAME_MISSING, 
	INVALID_RESOURCE_ID, 

}